import argparse
import json
import os
from datetime import datetime
from http import HTTPStatus
from pathlib import Path
from typing import Any, Dict, List

import dashscope
import requests
from dashscope.aigc.image_generation import ImageGeneration
from dashscope.api_entities.dashscope_response import Message


dashscope.base_http_api_url = "https://dashscope.aliyuncs.com/api/v1"


def download_image(url: str, filename: Path) -> None:
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        filename.parent.mkdir(parents=True, exist_ok=True)
        filename.write_bytes(response.content)
        print(f"保存成功: {filename}")
    except Exception as e:
        print(f"下载失败 {filename}: {e}")


def load_prompt_items(prompt_file: Path) -> List[Dict[str, Any]]:
    if not prompt_file.exists():
        raise SystemExit(f"未找到 prompt 文件: {prompt_file}")

    data = json.loads(prompt_file.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array in {prompt_file}")
    return [item for item in data if isinstance(item, dict)]


def normalize_prompt(item: Dict[str, Any]) -> str:
    return " ".join(str(item.get("prompt", "")).split())


def parse_num_images(item: Dict[str, Any]) -> int:
    value = item.get("num_images", 4)
    try:
        value = int(value)
    except Exception:
        value = 4
    return max(1, value)


def run_single_inference(api_key: str, item: Dict[str, Any], output_root: Path, *, model_name: str, image_size: str, index: int, total: int) -> None:
    prompt_id = str(item.get("id") or f"item_{index}")
    prompt_text = normalize_prompt(item)
    image_count = parse_num_images(item)
    save_dir = output_root / prompt_id

    if not prompt_text:
        print(f"跳过 {prompt_id}: prompt 为空")
        return

    print(f"\n[{index}/{total}] {prompt_id}")
    print(f"张数={image_count}, 尺寸={image_size}")

    message = Message(role="user", content=[{"text": prompt_text}])
    response = ImageGeneration.async_call(
        model=model_name,
        api_key=api_key,
        messages=[message],
        enable_sequential=True,
        n=image_count,
        size=image_size,
    )

    if response.status_code != HTTPStatus.OK:
        print(f"任务提交失败: {prompt_id}")
        print(f"错误码: {response.code}")
        print(f"错误信息: {response.message}")
        return

    task_id = response.output.task_id
    print(f"任务已提交, ID: {task_id}")

    status = ImageGeneration.wait(task=response, api_key=api_key)
    if status.output.task_status != "SUCCEEDED":
        print(f"任务执行失败, 状态: {status.output.task_status}")
        if hasattr(status, "code") and status.code:
            print(f"错误码: {status.code}")
        if hasattr(status, "message") and status.message:
            print(f"错误信息: {status.message}")
        return

    print("任务执行成功, 开始处理...")
    try:
        scheduled_time_str = status.output.get("scheduled_time") if hasattr(status.output, "get") else getattr(status.output, "scheduled_time", None)
        end_time_str = status.output.get("end_time") if hasattr(status.output, "get") else getattr(status.output, "end_time", None)
        if scheduled_time_str and end_time_str:
            def parse_time(t_str: str) -> datetime:
                fmt = "%Y-%m-%d %H:%M:%S.%f" if "." in t_str else "%Y-%m-%d %H:%M:%S"
                return datetime.strptime(t_str, fmt)

            actual_duration = (parse_time(end_time_str) - parse_time(scheduled_time_str)).total_seconds()
            print(f"模型生成耗时: {actual_duration:.2f} 秒")
    except Exception as e:
        print(f"时间解析异常: {e}")

    save_dir.mkdir(parents=True, exist_ok=True)
    content_list = status.output.choices[0].message.content
    image_idx = 0
    for item_content in content_list:
        img_url = item_content.get("image")
        if not img_url:
            continue
        filename = save_dir / f"view_{image_idx}.png"
        download_image(img_url, filename)
        image_idx += 1


def parse_args() -> argparse.Namespace:
    base_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Run Wan for prompts in a JSON file.")
    parser.add_argument(
        "--prompt-file",
        type=str,
        default=str(base_dir / "multi_view_prompts.json"),
        help="Path to the prompt JSON generated by generate_prompt.py.",
    )
    parser.add_argument(
        "--output-root",
        type=str,
        default=str(base_dir / "wan_result"),
        help="Directory for generated Wan images.",
    )
    parser.add_argument("--model", type=str, default="wan2.7-image-pro", help="Wan model name.")
    parser.add_argument("--image-size", type=str, default="2K", help="Image size passed to Wan.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    api_key = os.getenv("DASHSCOPE_API_KEY")
    if not api_key:
        raise SystemExit("请设置环境变量: DASHSCOPE_API_KEY")

    prompt_file = Path(args.prompt_file)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    items = load_prompt_items(prompt_file)
    print(f"读取到 {len(items)} 条 prompt")

    for index, item in enumerate(items, start=1):
        try:
            run_single_inference(
                api_key,
                item,
                output_root,
                model_name=args.model,
                image_size=args.image_size,
                index=index,
                total=len(items),
            )
        except Exception as e:
            prompt_id = item.get("id", f"item_{index}")
            print(f"{prompt_id} 运行异常: {e}")

    print(f"\n完成，结果保存在: {output_root}")


if __name__ == "__main__":
    main()
