import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

import torch

if torch.cuda.is_available():
    try:
        torch.backends.cuda.enable_flash_sdp(False)
        torch.backends.cuda.enable_mem_efficient_sdp(False)
        torch.backends.cuda.enable_math_sdp(True)
        if hasattr(torch.backends.cuda, "enable_cudnn_sdp"):
            torch.backends.cuda.enable_cudnn_sdp(False)
    except Exception:
        pass

import kiui
from pipeline_mvdream import MVDreamPipeline


def load_prompt_items(prompt_file: Path) -> List[Dict[str, Any]]:
    if not prompt_file.exists():
        raise SystemExit(f"未找到 prompt 文件: {prompt_file}")

    data = json.loads(prompt_file.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array in {prompt_file}")
    return [item for item in data if isinstance(item, dict)]


def normalize_prompt(item: Dict[str, Any]) -> str:
    return " ".join(str(item.get("prompt", "")).split())


def parse_num_images(item: Dict[str, Any]) -> int:
    value = item.get("num_images", 4)
    try:
        value = int(value)
    except Exception:
        value = 4
    return max(1, value)


def parse_args() -> argparse.Namespace:
    base_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Run MVDream for prompts in a JSON file.")
    parser.add_argument(
        "--prompt-file",
        type=str,
        default=str(base_dir / "multi_view_prompts.json"),
        help="Path to the prompt JSON generated by generate_prompt.py.",
    )
    parser.add_argument(
        "--output-root",
        type=str,
        default=str(base_dir / "mvdream_result"),
        help="Directory for generated MVDream images.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="ashawkey/mvdream-sd2.1-diffusers",
        help="Model path or Hugging Face repo.",
    )
    parser.add_argument("--guidance-scale", type=float, default=5.0)
    parser.add_argument("--num-inference-steps", type=int, default=30)
    parser.add_argument("--elevation", type=float, default=0.0)
    parser.add_argument("--device", type=str, default="cuda")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    prompt_file = Path(args.prompt_file)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    if args.device.startswith("cuda") and not torch.cuda.is_available():
        raise SystemExit("错误: 当前环境不可用 CUDA，但 --device 设置为 cuda。")

    dtype = torch.float16 if args.device.startswith("cuda") else torch.float32
    pipe = MVDreamPipeline.from_pretrained(
        args.model,
        torch_dtype=dtype,
    )
    pipe = pipe.to(args.device)

    items = load_prompt_items(prompt_file)
    print(f"读取到 {len(items)} 条 prompt")

    for index, item in enumerate(items, start=1):
        prompt_id = str(item.get("id") or f"item_{index}")
        prompt = normalize_prompt(item)
        num_images = parse_num_images(item)
        save_dir = output_root / prompt_id

        if not prompt:
            print(f"跳过 {prompt_id}: prompt 为空")
            continue

        print(f"[{index}/{len(items)}] {prompt_id}")
        save_dir.mkdir(parents=True, exist_ok=True)

        images = pipe(
            prompt,
            guidance_scale=args.guidance_scale,
            num_inference_steps=args.num_inference_steps,
            elevation=args.elevation,
            num_frames=num_images,
            device=torch.device(args.device),
        )

        for view_idx, image in enumerate(images):
            output_path = save_dir / f"view_{view_idx}.jpg"
            kiui.write_image(str(output_path), image)

    print(f"\n完成，结果保存在: {output_root}")


if __name__ == "__main__":
    main()
